### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by useman** [zhaodice/qemu-anti-detection#12]
Where can I find files?
/passthough/vbios_gvt_uefi.rom
/passthough/OVMF_VARS.fd

And what are these files for in the directory [qemu-anti-detection](https://github.com/zhaodice/qemu-anti-detection)/deb/?

**Comment by zhaodice** [comment]
OVMF_VARS.fd can auto create by qemu if it doesn't exit,
[vbios_gvt_uefi.rom.tar.gz](https://github.com/zhaodice/qemu-anti-detection/files/11264171/vbios_gvt_uefi.rom.tar.gz)

**Comment by zhaodice** [comment]
`qemu-anti-detection/deb/` is a installing package by myself compile result for ubuntu 22 , you also can build it by your system follow my readme
