### ISSUE TITLE
Failed at compilation

### ISSUE THREAD

**Issue by albatror** [zhaodice/qemu-anti-detection#13]
**ubuntu last release and updated.**
After trying to apply the patch 7.2: 
`git apply qemu-7.2.patch
error: le patch a échoué : block/vhdx.c:2007
error: block/vhdx.c : le patch ne s'applique pas
error: le patch a échoué : hw/i386/pc.c:103
error: hw/i386/pc.c : le patch ne s'applique pas
error: le patch a échoué : hw/nvme/ctrl.c:7375
error: hw/nvme/ctrl.c : le patch ne s'applique pas
error: le patch a échoué : hw/usb/dev-network.c:99
error: hw/usb/dev-network.c : le patch ne s'applique pas
error: le patch a échoué : include/hw/pci/pci.h:72
error: include/hw/pci/pci.h : le patch ne s'applique pas
error: le patch a échoué : target/s390x/tcg/misc_helper.c:329
error: target/s390x/tcg/misc_helper.c : le patch ne s'applique pas
`
After make: 
`[935/2777] Compiling C object libblock.fa.p/block_curl.c.o
FAILED: libblock.fa.p/block_curl.c.o 
cc -m64 -mcx16 -Ilibblock.fa.p -I. -I../qemu -Iqapi -Itrace -Iui -Iui/shader -Iblock -I/usr/include/p11-kit-1 -I/usr/include/x86_64-linux-gnu -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=auto -Wall -Winvalid-pch -Werror -std=gnu11 -O2 -g -isystem /home/t3zo/qemu/linux-headers -isystem linux-headers -iquote . -iquote /home/t3zo/qemu -iquote /home/t3zo/qemu/include -iquote /home/t3zo/qemu/disas/libvixl -iquote /home/t3zo/qemu/tcg/i386 -pthread -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-declaration -Wold-style-definition -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=2 -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -fstack-protector-strong -fPIE -MD -MQ libblock.fa.p/block_curl.c.o -MF libblock.fa.p/block_curl.c.o.d -o libblock.fa.p/block_curl.c.o -c ../qemu/block/curl.c
../qemu/block/curl.c: In function ‘curl_init_state’:
../qemu/block/curl.c:515:9: error: ‘CURLOPT_PROTOCOLS’ is deprecated: since 7.85.0. Use CURLOPT_PROTOCOLS_STR [-Werror=deprecated-declarations]
  515 |         if (curl_easy_setopt(state->curl, CURLOPT_PROTOCOLS, PROTOCOLS) ||
      |         ^~
In file included from ../qemu/block/curl.c:34:
/usr/include/x86_64-linux-gnu/curl/curl.h:1749:3: note: declared here
 1749 |   CURLOPTDEPRECATED(CURLOPT_PROTOCOLS, CURLOPTTYPE_LONG, 181,
      |   ^~~~~~~~~~~~~~~~~
../qemu/block/curl.c:516:13: error: ‘CURLOPT_REDIR_PROTOCOLS’ is deprecated: since 7.85.0. Use CURLOPT_REDIR_PROTOCOLS_STR [-Werror=deprecated-declarations]
  516 |             curl_easy_setopt(state->curl, CURLOPT_REDIR_PROTOCOLS, PROTOCOLS)) {
      |             ^~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/curl/curl.h:1755:3: note: declared here
 1755 |   CURLOPTDEPRECATED(CURLOPT_REDIR_PROTOCOLS, CURLOPTTYPE_LONG, 182,
      |   ^~~~~~~~~~~~~~~~~
../qemu/block/curl.c: In function ‘curl_open’:
../qemu/block/curl.c:799:5: error: ‘CURLINFO_CONTENT_LENGTH_DOWNLOAD’ is deprecated: since 7.55.0. Use CURLINFO_CONTENT_LENGTH_DOWNLOAD_T [-Werror=deprecated-declarations]
  799 |     if (curl_easy_getinfo(state->curl, CURLINFO_CONTENT_LENGTH_DOWNLOAD, &d)) {
      |     ^~
/usr/include/x86_64-linux-gnu/curl/curl.h:2858:3: note: declared here
 2858 |   CURLINFO_CONTENT_LENGTH_DOWNLOAD
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.
make: *** [Makefile:163 : run-ninja] Erreur 1
`
Any advice? Thks in advance and thks for your work.

**Comment by zhaodice** [comment]
please downgrade curl library version OR do compilation latest qemu:

```
#assume you have cleaned old qemu folder.

git clone https://gitlab.com/qemu-project/qemu/ -b v8.0.0 --depth 1 --recursive
wget https://raw.githubusercontent.com/zhaodice/qemu-anti-detection/main/qemu-8.0.5.patch
git apply qemu-8.0.5.patch
```

or ensure you selected right branch.
```
git clone https://gitlab.com/qemu-project/qemu/ -b v7.2.0 --depth 1 --recursive
wget https://raw.githubusercontent.com/zhaodice/qemu-anti-detection/main/qemu-7.2.patch
git apply qemu-7.2.patch
```

**Comment by zhaodice** [comment]
Downgrading curl library may effect your environment, if you want 7.2 only, the best way is making a docker container which is suitable version for qemu 7.2 to compile it.
