### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by GiuJunWang** [zhaodice/qemu-anti-detection#15]
![Uploading image.png…]()
经过老哥教程装完后还是没有通过，我是否缺少某些环节

**Comment by GiuJunWang** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/9e39fe48-4838-4a70-bd04-cdf30f2dbe9a)

**Comment by zhaodice** [comment]
当然咯，你还要改配置

**Comment by zhaodice** [comment]
看我“QEMU Config Reference Resources”这一栏
xml改成
```
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
...
  <qemu:commandline>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=0,version=UX305UA.201"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=1,manufacturer=ASUS,product=UX305UA,version=2021.1"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=2,manufacturer=Intel,version=2021.5,product=Intel i9-12900K"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=3,manufacturer=XBZJ"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=000000,part=0000"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=4,manufacturer=Intel,max-speed=4800,current-speed=4800"/>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,family=6,model=158,stepping=2,model_id=Intel(R) Core(TM) i9-12900K CPU @ 2.60GHz,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,-hypervisor,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_relaxed,kvm=off,hv_vendor_id=intel"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35,kernel_irqchip=on"/>
  </qemu:commandline>
</domain>
```

**Comment by zhaodice** [comment]
这里面的机器信息都可以随意修改，
qemu的补丁仅仅是帮助你屏蔽掉【xml做不到的部分】
你xml可以做到的部分还是要写的啊

**Comment by zhaodice** [comment]
![Screenshot_20230517_233533](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/be8fd894-9456-4f84-b4db-3608d3b21c36)

**Comment by GiuJunWang** [comment]
多谢  我用的virt-manager配置没有修改成功

**Comment by GiuJunWang** [comment]
我试试用和您一样的虚机机管理器再试试

**Comment by GiuJunWang** [comment]
> ![Screenshot_20230517_233533](https://user-images.githubusercontent.com/63996691/239003592-be8fd894-9456-4f84-b4db-3608d3b21c36.png)

我现在是这个问题，当我修改这个配置文件应用之后，再次查看这些增加的内容就消失了

**Comment by GiuJunWang** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/a9f33798-0e0a-4f6c-a589-3239460027db)
请看，内容写入后并没有生效，有点无奈

**Comment by zhaodice** [comment]
删除虚拟机，重新创建,勾选“在安装前自定义配置”
记下“UUID”，清空xml所有内容，粘贴如下
```
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <name>Entertainment</name>
  <uuid>这里替换成你上次记的对应的UUID</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">1548288</memory>
  <currentMemory unit="KiB">1548288</currentMemory>
  <memoryBacking>
    <source type="memfd"/>
    <access mode="shared"/>
  </memoryBacking>
  <vcpu placement="static">12</vcpu>
  <os firmware="efi">
    <type arch="x86_64" machine="pc-q35-7.0">hvm</type>
    <loader/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv mode="custom">
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
      <vendor_id state="on" value="GenuineIntel"/>
    </hyperv>
    <kvm>
      <hidden state="on"/>
    </kvm>
    <vmport state="off"/>
    <smm state="on"/>
    <ioapic driver="kvm"/>
  </features>
  <cpu mode="host-model" check="partial"/>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <qemu:commandline>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=0,version=UX305UA.201"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=1,manufacturer=ASUS,product=UX305UA,version=2021.1"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=2,manufacturer=Intel,version=2021.5,product=Intel i9-12900K"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=3,manufacturer=XBZJ"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=000000,part=0000"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=4,manufacturer=Intel,max-speed=4800,current-speed=4800"/>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,family=6,model=158,stepping=2,model_id=Intel(R) Core(TM) i9-12900K CPU @ 2.60GHz,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35,kernel_irqchip=on"/>
  </qemu:commandline>
</domain>

```

然后设备自己加，各种设置，虚拟机内存大小自己改

**Comment by GiuJunWang** [comment]
我非常感谢老哥提供的帮助,但是依然没有成功，已然崩溃

**Comment by GiuJunWang** [comment]
目前修改之后添加完设备进不去系统

**Comment by GiuJunWang** [comment]
老哥能发个镜像+配置嘛

**Comment by zhaodice** [comment]
镜像是没用的，你这个检测就缺XML参数

**Comment by zhaodice** [comment]
> 目前修改之后添加完设备进不去系统

你倒是截图啊哪里进不去我怎么知道怎么进不去

**Comment by zhaodice** [comment]
1.你添加的是virtio设备，你不知道virtio是虚拟机专用设备吗，用这种设备等于在脸上贴着“我是虚拟机”了，建议SATA驱动器，IDE虽然最垃圾但是最万能
2.启动如果没有报错，只是黑屏，自己检查显卡是否添加，另外给你个忠告建议显卡直通，因为虚拟的显卡永远无法抵抗最前沿的游戏反作弊检测，如果只是想哄骗一下垃圾加密壳，那显卡就选QXL
3.引导选项里到底有没有勾选自己的C盘qcow2文件，或者iso光驱
4.自己贴出启动失败到底报的什么错，到底现象是什么，连个截图都没有我给你虚空问诊？
5.我给你的xml是基于windows10的，注意看
```
<libosinfo:os id="http://microsoft.com/win/10"/>
```
你需要自己修改它为对应正确的OS

开源社区的玩意，想不折腾就拿来用，那是不可能的

**Comment by zhaodice** [comment]
引导选项选中C盘qcow2文件/DVD驱动器了吗？是SATA吗？
![Screenshot_20230519_000059](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/3d92c6b3-1fc0-4dca-a046-ac63cec85177)

这个地方我显卡是None但你别盲目学我，我是因为直通了一张MDEV核显，我是有显卡的，你照搬肯定不行啊
![Screenshot_20230519_000223](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/3d19c156-41f1-4697-ad94-f7d9ba59c8bb)

其他地方我猜不出来了建议截图，无图言吊

**Comment by zhaodice** [comment]
如果还是解决不了建议你留下QQ我加你

**Comment by GiuJunWang** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/1410bb42-d9a3-45b7-a7b5-4d993cda9efd)

**Comment by GiuJunWang** [comment]
感谢！qq：18688355

**Comment by GiuJunWang** [comment]
我的最终目的就是过一些壳的虚拟机检测

**Comment by GiuJunWang** [comment]
显卡选择qxl报以下错误：
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/d5f292be-8840-4f5f-83d4-89adc6d56096)

**Comment by GiuJunWang** [comment]
<devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/var/lib/libvirt/images/win7.qcow2"/>
      <target dev="sda" bus="sata"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/root/Desktop/cn_windows_7_ultimate_with_sp1_x86_dvd_u_677486.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
    </disk>
    <controller type="usb" model="ich9-ehci1"/>
    <controller type="usb" model="ich9-uhci1">
      <master startport="0"/>
    </controller>
    <controller type="usb" model="ich9-uhci2">
      <master startport="2"/>
    </controller>
    <controller type="usb" model="ich9-uhci3">
      <master startport="4"/>
    </controller>
    <controller type="pci" model="pcie-root"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <interface type="network">
      <source network="default"/>
      <mac address="52:54:00:15:72:42"/>
      <model type="e1000e"/>
    </interface>
    <console type="pty"/>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" port="-1"/>
    <video>
      <model type="vga"/>
    </video>
  </devices>

**Comment by GiuJunWang** [comment]
<devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <disk type="file" device="disk">
      <driver name="qemu" type="qcow2" discard="unmap"/>
      <source file="/var/lib/libvirt/images/win7.qcow2"/>
      <target dev="sda" bus="sata"/>
    </disk>
    <disk type="file" device="cdrom">
      <driver name="qemu" type="raw"/>
      <source file="/root/Desktop/cn_windows_7_ultimate_with_sp1_x86_dvd_u_677486.iso"/>
      <target dev="sdb" bus="sata"/>
      <readonly/>
    </disk>
    <controller type="usb" model="ich9-ehci1"/>
    <controller type="usb" model="ich9-uhci1">
      <master startport="0"/>
    </controller>
    <controller type="usb" model="ich9-uhci2">
      <master startport="2"/>
    </controller>
    <controller type="usb" model="ich9-uhci3">
      <master startport="4"/>
    </controller>
    <controller type="pci" model="pcie-root"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <controller type="pci" model="pcie-root-port"/>
    <interface type="network">
      <source network="default"/>
      <mac address="52:54:00:15:72:42"/>
      <model type="e1000e"/>
    </interface>
    <console type="pty"/>
    <input type="tablet" bus="usb"/>
    <graphics type="vnc" port="-1"/>
    <video>
      <model type="vga"/>
    </video>
  </devices>

**Comment by GiuJunWang** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/be6978f0-ce79-4bf5-a64a-48071464f0e8)
有没有可能是这里引起的，但是我每次配置的这些，应用启动之后就直接
消失，不知道为啥
![image](https://github.com/zhaodice/qemu-anti-detection/assets/127731968/25f06c60-8f3b-477c-b637-f64815b75cf6)

**Comment by GiuJunWang** [comment]
感谢，我已经解决了，是因为我没有设置<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">

**Comment by zhaodice** [comment]
没有被壳检测了吧?
