### ISSUE TITLE
Help with compiling

### ISSUE THREAD

**Issue by Puppeteer-rg** [zhaodice/qemu-anti-detection#16]
When I try to compile for the qemu version 7.2, it gives me this error:

```
In file included from /usr/include/linux/btrfs.h:29,
                 from ../qemu/linux-user/syscall.c:163:
/usr/include/linux/fs.h:50:8: error: redefinition of ‘struct file_clone_range’
   50 | struct file_clone_range {
      |        ^~~~~~~~~~~~~~~~
../qemu/linux-user/syscall.c:129:8: note: originally defined here
  129 | struct file_clone_range {
      |        ^~~~~~~~~~~~~~~~
```

**Comment by zhaodice** [comment]
https://lists.openembedded.org/g/openembedded-core/topic/patchv2_qemu_fix_building/97161162

this is `glibc 2.36 ` 's BUG, please upgrade or downgrade to the non-bug version

**Comment by Puppeteer-rg** [comment]
I've fixed it by applying this patch
https://src.fedoraproject.org/rpms/qemu/c/c59732e734abe4f9d56442be1903f022c50602ad?branch=rawhide
