### ISSUE TITLE
Support QEMU 8.0.2

### ISSUE THREAD

**Issue by Gustav0ar** [zhaodice/qemu-anti-detection#17]
Can you please support latest stable v8.0.2?

Currently I get this error:

```
❯ git apply qemu-8.0.5.patch
error: patch failed: hw/i386/pc.c:112
error: hw/i386/pc.c: patch does not apply
```

**Comment by zhaodice** [comment]
I am planing to do this in the five days, you can use old version first

**Comment by zhaodice** [comment]
https://raw.githubusercontent.com/zhaodice/qemu-anti-detection/main/qemu-8.0.2.patch
