### ISSUE TITLE
Meson Build Error on Arch

### ISSUE THREAD

**Issue by verifizieren** [zhaodice/qemu-anti-detection#18]
Hey when I tried doing exactly what the tutorials says, i get this error:
`
Configuring alpha-softmmu-config-devices.mak with command

../meson.build:2622:25: ERROR: Command `/usr/bin/python /opt/Qemu/qemu/scripts/minikconf.py --defconfig alpha-softmmu-config-devices.mak /opt/Qemu/qemu/build/meson-private/alpha-softmmu-config-devices.mak.d /opt/Qemu/qemu/configs/devices/alpha-softmmu/default.mak /opt/Qemu/qemu/Kconfig CONFIG_TPM=y CONFIG_SPICE=y CONFIG_IVSHMEM=y CONFIG_OPENGL=y CONFIG_X11=y CONFIG_VHOST_USER=y CONFIG_VHOST_VDPA=y CONFIG_VHOST_KERNEL=y CONFIG_VIRTFS=y CONFIG_LINUX=y CONFIG_MULTIPROCESS_ALLOWED=y CONFIG_TCG=y CONFIG_ALPHA=y` failed with status 1.

A full log can be found at /opt/Qemu/qemu/build/meson-logs/meson-log.txt

ERROR: meson setup failed

[max@Archie qemu]$ 
`
I am on Arch, that might be the reason but I don't really know. I have been trying to build qemu for 2 days now but it kept failing.

**Comment by verifizieren** [comment]
This is a snippet from the meson-log.txt:
`
--- stderr ---
Traceback (most recent call last):
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 700, in <module>
    parser.parse_file(fp)
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 362, in parse_file
    self.parse_config()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 575, in parse_config
    self.parse_clause()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 564, in parse_clause
    self.do_include(val)
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 413, in do_include
    KconfigParser(self.data).parse_file(fp)
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 362, in parse_file
    self.parse_config()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 575, in parse_config
    self.parse_clause()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 564, in parse_clause
    self.do_include(val)
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 413, in do_include
    KconfigParser(self.data).parse_file(fp)
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 362, in parse_file
    self.parse_config()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 575, in parse_config
    self.parse_clause()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 566, in parse_clause
    self.parse_declaration()
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 551, in parse_declaration
    var = self.parse_var()
          ^^^^^^^^^^^^^^^^
  File "/opt/Qemu/qemu/scripts/minikconf.py", line 435, in parse_var
    raise KconfigParserError(self, 'Expected identifier')
KconfigParserError: In file included from /opt/Qemu/qemu/Kconfig:6:
In file included from /opt/Qemu/qemu/hw/Kconfig:57:
/opt/Qemu/qemu/hw/mips/Kconfig:60:8: Expected identifier before "="



../meson.build:2622:25: ERROR: Command `/usr/bin/python /opt/Qemu/qemu/scripts/minikconf.py --defconfig alpha-softmmu-config-devices.mak /opt/Qemu/qemu/build/meson-private/alpha-softmmu-config-devices.mak.d /opt/Qemu/qemu/configs/devices/alpha-softmmu/default.mak /opt/Qemu/qemu/Kconfig CONFIG_TPM=y CONFIG_SPICE=y CONFIG_IVSHMEM=y CONFIG_OPENGL=y CONFIG_X11=y CONFIG_VHOST_USER=y CONFIG_VHOST_VDPA=y CONFIG_VHOST_KERNEL=y CONFIG_VIRTFS=y CONFIG_LINUX=y CONFIG_MULTIPROCESS_ALLOWED=y CONFIG_TCG=y CONFIG_ALPHA=y` failed with status 1.

`

**Comment by zhaodice** [comment]
You cannot use python2 , it is outdated, please replace it with python3 :
```
root@LXC-ProxmoxCompile:~/patchgen# python3 --version
Python 3.9.2
root@LXC-ProxmoxCompile:~/patchgen# 
```
Because you are using python2 , there is a possible , you are  using the old system enviroment
to build latest qemu, I am very recommending you to compile it within Docker or other virtual enviroment, in case of your machine system broken .

**Comment by verifizieren** [comment]
> You cannot use python2 , it is outdated, please replace it with python3 :
> 
> ```
> 
> root@LXC-ProxmoxCompile:~/patchgen# python3 --version
> 
> Python 3.9.2
> 
> root@LXC-ProxmoxCompile:~/patchgen# 
> 
> ```
> 
> Because you are using python2 , there is a possible , you are  using the old system enviroment
> 
> to build latest qemu, I am very recommending you to compile it within Docker or other virtual enviroment, in case of your machine system broken .

Well im am using Python3, anyways when compiling trough a Ubuntu vm, everything works since I can get all the build-dep easily on there but I don’t know how to d that on Arch. Also when I try to build the compiled version on my Arch system, it fails again so what could be the issue here?

**Comment by zhaodice** [comment]
did you try to build it on arch docker container ? I guess your machine has some incompatible package or config, make pure arch environment and try it again. don't forget to upgrade your arch system to the latest version.

**Comment by verifizieren** [comment]
Yes that worked, thanks!
