### ISSUE TITLE
still be dectected with vmp 3.2+

### ISSUE THREAD

**Issue by chenbowen9706** [zhaodice/qemu-anti-detection#20]
after patch qemu7.0.0 and complie it and fix some rdtsc attacks my guest windows still got dectected with vmp3.2+ version

**Comment by chenbowen9706** [comment]
used al-hasker to got this dectected info:
[*] Checking Local Descriptor Table location                                                       [ BAD  ]
[*] Checking power capabilities                                                                    [ BAD  ]
[*] Checking CPU fan using WMI                                                                     [ BAD  ]
[*] Checking Win32_CacheMemory with WMI                                                            [ BAD  ]
[*] Checking Win32_MemoryDevice with WMI                                                           [ BAD  ]
[*] Checking Win32_VoltageProbe with WMI                                                           [ BAD  ]
[*] Checking Win32_PortConnector with WMI                                                          [ BAD  ]
[*] Checking ThermalZoneInfo performance counters with WMI                                         [ BAD  ]
[*] Checking CIM_Memory with WMI                                                                   [ BAD  ]
[*] Checking CIM_Sensor with WMI                                                                   [ BAD  ]
[*] Checking CIM_NumericSensor with WMI                                                            [ BAD  ]
[*] Checking CIM_TemperatureSensor with WMI                                                        [ BAD  ]
[*] Checking CIM_VoltageSensor with WMI                                                            [ BAD  ]
[*] Checking CIM_PhysicalConnector with WMI                                                        [ BAD  ]
[*] Checking CIM_Slot with WMI                                                                     [ BAD  ]
[*] Checking for Hyper-V global objects                                                            [ BAD  ]

**Comment by chenbowen9706** [comment]
exclude wmi check still got this:
[*] Checking Local Descriptor Table location                                                       [ BAD  ]  
 [*] Checking power capabilities                                                                    [ BAD  ]                                                                                                             
[*] Checking for Hyper-V global objects                                                            [ BAD  ]

**Comment by zhaodice** [comment]
can you give a simple exe(VMP exe)

**Comment by zhaodice** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/c9950672-281a-4a78-a778-efee433e56ea)
works fine here, please check your vm config:
```
<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
...
  <qemu:commandline>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=0,version=UX305UA.201"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=1,manufacturer=ASUS,product=UX305UA,version=2021.1"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=2,manufacturer=Intel,version=2021.5,product=Intel i9-12900K"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=3,manufacturer=XBZJ"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=000000,part=0000"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=4,manufacturer=Intel,max-speed=4800,current-speed=4800"/>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,family=6,model=158,stepping=2,model_id=Intel(R) Core(TM) i9-12900K CPU @ 2.60GHz,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35,kernel_irqchip=on"/>
  </qemu:commandline>
</domain>
```

**Comment by chenbowen9706** [comment]
![1](https://github.com/zhaodice/qemu-anti-detection/assets/129165559/cbb221fa-8aea-4272-9093-4678abd2a151)
i think we use the same exe file packed with vmp protect

**Comment by chenbowen9706** [comment]
`<domain xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0" type="kvm">
  <name>Entertainment</name>
  <uuid>59854440-90fb-4761-bfc6-89bec8d7079a</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
      <libosinfo:os id="http://microsoft.com/win/10"/>
    </libosinfo:libosinfo>
  </metadata>
  <memory unit="KiB">1548288</memory>
  <currentMemory unit="KiB">1548288</currentMemory>
  <memoryBacking>
    <source type="memfd"/>
    <access mode="shared"/>
  </memoryBacking>
  <vcpu placement="static">12</vcpu>
  <os firmware="efi">
    <type arch="x86_64" machine="pc-q35-7.0">hvm</type>
    <loader/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <hyperv mode="custom">
      <relaxed state="on"/>
      <vapic state="on"/>
      <spinlocks state="on" retries="8191"/>
      <vendor_id state="on" value="GenuineIntel"/>
    </hyperv>
    <kvm>
      <hidden state="on"/>
    </kvm>
    <vmport state="off"/>
    <smm state="on"/>
    <ioapic driver="kvm"/>
  </features>
  <cpu mode="host-model" check="partial"/>
  <clock offset="localtime">
    <timer name="rtc" tickpolicy="catchup"/>
    <timer name="pit" tickpolicy="delay"/>
    <timer name="hpet" present="no"/>
    <timer name="hypervclock" present="yes"/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled="no"/>
    <suspend-to-disk enabled="no"/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <controller type="usb" index="0" model="qemu-xhci" ports="15">
      <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
    </controller>
    <controller type="pci" index="0" model="pcie-root"/>
    <controller type="pci" index="1" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="1" port="0x8"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="2" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="2" port="0x9"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x1"/>
    </controller>
    <controller type="pci" index="3" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="3" port="0xa"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x2"/>
    </controller>
    <controller type="pci" index="4" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="4" port="0xb"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x3"/>
    </controller>
    <controller type="pci" index="5" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="5" port="0xc"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x4"/>
    </controller>
    <controller type="pci" index="6" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="6" port="0xd"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x5"/>
    </controller>
    <controller type="pci" index="7" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="7" port="0xe"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x6"/>
    </controller>
    <controller type="pci" index="8" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="8" port="0xf"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x01" function="0x7"/>
    </controller>
    <controller type="pci" index="9" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="9" port="0x10"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0" multifunction="on"/>
    </controller>
    <controller type="pci" index="10" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="10" port="0x11"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x1"/>
    </controller>
    <controller type="pci" index="11" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="11" port="0x12"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x2"/>
    </controller>
    <controller type="pci" index="12" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="12" port="0x13"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x3"/>
    </controller>
    <controller type="pci" index="13" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="13" port="0x14"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x4"/>
    </controller>
    <controller type="pci" index="14" model="pcie-root-port">
      <model name="pcie-root-port"/>
      <target chassis="14" port="0x15"/>
      <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x5"/>
    </controller>
    <controller type="sata" index="0">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x1f" function="0x2"/>
    </controller>
    <input type="mouse" bus="ps2"/>
    <input type="keyboard" bus="ps2"/>
    <audio id="1" type="none"/>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
      </source>
      <boot order="1"/>
      <address type="pci" domain="0x0000" bus="0x02" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
      </source>
      <address type="pci" domain="0x0000" bus="0x03" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
      </source>
      <address type="pci" domain="0x0000" bus="0x04" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="pci" managed="yes">
      <source>
        <address domain="0x0000" bus="0x01" slot="0x00" function="0x1"/>
      </source>
      <address type="pci" domain="0x0000" bus="0x05" slot="0x00" function="0x0"/>
    </hostdev>
    <hostdev mode="subsystem" type="usb" managed="yes">
      <source>
        <vendor id="0x1c4f"/>
        <product id="0x0002"/>
      </source>
      <address type="usb" bus="0" port="1"/>
    </hostdev>
    <hostdev mode="subsystem" type="usb" managed="yes">
      <source>
        <vendor id="0x046d"/>
        <product id="0xc08b"/>
      </source>
      <address type="usb" bus="0" port="2"/>
    </hostdev>
    <memballoon model="none"/>
  </devices>
  <qemu:commandline>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=0,version=UX305UA.201"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=1,manufacturer=ASUS,product=UX305UA,version=2021.1"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=2,manufacturer=Intel,version=2021.5,product=Intel i9-12900K"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=3,manufacturer=XBZJ"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=000000,part=0000"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=4,manufacturer=Intel,max-speed=4800,current-speed=4800"/>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,family=6,model=158,stepping=2,model_id=Intel(R) Core(TM) i9-12900K CPU @ 2.60GHz,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35,kernel_irqchip=on"/>
  </qemu:commandline>
</domain>
`

**Comment by zhaodice** [comment]
can I check your qemu xml fie?

**Comment by chenbowen9706** [comment]
i had upload before

**Comment by zhaodice** [comment]
> i had upload before

I didn't see your xml config file ,are you using the command to start qemu?

**Comment by zhaodice** [comment]
add follows to your qemu args:
```
-cpu host,-hypervisor,kvm=off,hv_vendor_id='MiHoYo',vmware-cpuid-freq=false,enforce=false,host-phys-bits=true -smbios type=0,version=UX305UA.201 -smbios type=2,manufacturer=Intel,version=2021.5,product='MiHoYoSuperX' -smbios type=3,manufacturer=MiHoYo -smbios type=17,manufacturer=MiHoYo,loc_pfx=DDR5,speed=4800,serial=114514,part=1145 -smbios type=4,manufacturer=Intel,max-speed=4800,current-speed=4800 -acpitable oem_id=mhy,oem_table_id=mihoyo,asl_compiler_id=ASUS,asl_compiler_rev=114514,oem_rev=191981
```

**Comment by chenbowen9706** [comment]
actually im just copy your xml into my libvirt and just add some dev

**Comment by zhaodice** [comment]
> actually im just copy your xml into my libvirt and just add some dev

run the command:
```
ps -ax | grep qemu
```
I want to see your process 's args

**Comment by chenbowen9706** [comment]
file:///media/anpanman/4C66CCEA66CCD5BC/win10.xml

**Comment by zhaodice** [comment]
please click "Attach files by dragging & dropping, selecting or pasting them." to upload file

**Comment by chenbowen9706** [comment]
[win10.txt](https://github.com/zhaodice/qemu-anti-detection/files/12104325/win10.txt)

**Comment by zhaodice** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/687f6545-b43b-441f-9398-b119b01a479f)
take a screenshot this

**Comment by chenbowen9706** [comment]
![无标题](https://github.com/zhaodice/qemu-anti-detection/assets/129165559/f671a390-9987-4e29-b77a-33af5d2fcc69)

**Comment by chenbowen9706** [comment]
the network and disk is passthrou with pci

**Comment by zhaodice** [comment]
I think my "al-khaser.exe" is different to you ,can you upload here?

**Comment by zhaodice** [comment]
[al-khaser.zip](https://github.com/zhaodice/qemu-anti-detection/files/12104424/al-khaser.zip)
or you test it and report

**Comment by chenbowen9706** [comment]
[KHASER.zip](https://github.com/zhaodice/qemu-anti-detection/files/12104431/KHASER.zip)
THIS IS MINE

**Comment by chenbowen9706** [comment]
pafish64 log:
![1](https://github.com/zhaodice/qemu-anti-detection/assets/129165559/c984a79f-605f-43bf-9bb3-85da6fdee18c)

**Comment by chenbowen9706** [comment]
“
[*] Delay value is set to 10 minutes ...
[*] Performing a sleep using NtDelayExecution ...
”
i think u should change 10 minute wait to 1 haha..
and this is my log which used your [al-khaser.zip]
[k-haser-log.txt](https://github.com/zhaodice/qemu-anti-detection/files/12104464/k-haser-log.txt)

**Comment by zhaodice** [comment]
run the 
```
ps -ax | grep qemu
```
on your host machine, and report

**Comment by chenbowen9706** [comment]
[Uploading ps log.txt…]()

**Comment by chenbowen9706** [comment]
[ps log.txt](https://github.com/zhaodice/qemu-anti-detection/files/12104494/ps.log.txt)

**Comment by zhaodice** [comment]
ok, then , upload `/usr/bin/qemu-system-x86_64` here

**Comment by chenbowen9706** [comment]
[qemu-system-x86_64.zip](https://github.com/zhaodice/qemu-anti-detection/files/12104516/qemu-system-x86_64.zip)

**Comment by chenbowen9706** [comment]
i had used 8.0.2 and 7.0.0 they are both dectected with vmp3.x

**Comment by zhaodice** [comment]
can you remove your rdtsc ? I know vmp didn't detect it.

**Comment by chenbowen9706** [comment]
yea i will reboot and do it wait me a few minute

**Comment by zhaodice** [comment]
did you enable hyper-v on your windows? if it is yes ,please close it

**Comment by zhaodice** [comment]
![image](https://github.com/zhaodice/qemu-anti-detection/assets/63996691/3e099464-8d0c-42dc-ab3f-fe0605980cb1)
disable hyper-v

**Comment by chenbowen9706** [comment]
okay it works now when i dont patch rdtsc clock ,i will close the issu soon, can u send me your qq or wechat? i want to do more communication with you

**Comment by zhaodice** [comment]
q1619180854
