### ISSUE TITLE
Is it possible to use virtio with this?

### ISSUE THREAD

**Issue by verifizieren** [zhaodice/qemu-anti-detection#21]
Okay so basically I used the latest patch to make a version for the newest qemu version but that issue is also present when applying the patch to v8.0.3. For some reason I am not able to use virtio on the win guest but I don't really know what that is the case. It might be, because of some strings that virtio uses to get the devices? Anyways how could I fix that?

**Comment by zhaodice** [comment]
virtio has a known device pcie id , and virtio device keyword , which can be detected by others software, the best important reason is it have to install virtio driver , you have to patch the virtio driver to hide itself(event you haven't driver signature for Micro**shit** Windows, disable signature mode is banned by anticheat).. it is too big to finish the project.

**Comment by zhaodice** [comment]
so, I have banned the virtio, and hide virtio from guest machine, it is the best easy way

**Comment by verifizieren** [comment]
Ohh okay I understand, I can try looking into that but thanks for letting me know!

**Comment by fecet** [comment]
How can I try to enable it and test if it's still work for me ? It's possible some anticheat not so strong

**Comment by zhaodice** [comment]
> How can I try to enable it and test if it's still work for me ? It's possible some anticheat not so strong

yes you can, you can remove the VIRTIO DEVICE id from the patch file. it may works fine

**Comment by fecet** [comment]
Did you mean this part
```
diff --git a/hw/input/virtio-input-hid.c b/hw/input/virtio-input-hid.c
index a7a244a..bc16b1e 100644
--- a/hw/input/virtio-input-hid.c
+++ b/hw/input/virtio-input-hid.c
@@ -16,9 +16,9 @@
 
 #include "standard-headers/linux/input.h"
 
-#define VIRTIO_ID_NAME_KEYBOARD "QEMU Virtio Keyboard"
-#define VIRTIO_ID_NAME_MOUSE    "QEMU Virtio Mouse"
-#define VIRTIO_ID_NAME_TABLET   "QEMU Virtio Tablet"
+#define VIRTIO_ID_NAME_KEYBOARD "ASUS Keyboard"
+#define VIRTIO_ID_NAME_MOUSE    "ASUS Mouse"
+#define VIRTIO_ID_NAME_TABLET   "ASUS Tablet"
```
That's all I find looks revelant

**Comment by zhaodice** [comment]
> Did you mean this part
> 
> ```
> diff --git a/hw/input/virtio-input-hid.c b/hw/input/virtio-input-hid.c
> index a7a244a..bc16b1e 100644
> --- a/hw/input/virtio-input-hid.c
> +++ b/hw/input/virtio-input-hid.c
> @@ -16,9 +16,9 @@
>  
>  #include "standard-headers/linux/input.h"
>  
> -#define VIRTIO_ID_NAME_KEYBOARD "QEMU Virtio Keyboard"
> -#define VIRTIO_ID_NAME_MOUSE    "QEMU Virtio Mouse"
> -#define VIRTIO_ID_NAME_TABLET   "QEMU Virtio Tablet"
> +#define VIRTIO_ID_NAME_KEYBOARD "ASUS Keyboard"
> +#define VIRTIO_ID_NAME_MOUSE    "ASUS Mouse"
> +#define VIRTIO_ID_NAME_TABLET   "ASUS Tablet"
> ```
> 
> That's all I find looks revelant

yes, you can search keyword "VIRTIO" and remove the patch
