### ISSUE TITLE
great patches

### ISSUE THREAD

**Issue by uragan1987** [zhaodice/qemu-anti-detection#22]

**Comment by uragan1987** [comment]
im using qemu kvm 7.0.0

whats your exp with newer version,  should i update to newer versions?
is this a big performance boost?

**Comment by verifizieren** [comment]
I don't know if virtio is working for you but if you dont care about that you could get the latest version and patch the source yourself.

**Comment by zhaodice** [comment]
I didn't see any big performance boost on the newer version...

**Comment by romanholidaypancakes** [comment]
I found some tips about qemu performance improvement, I haven't tried it, maybe it will help you.

https://leduccc.medium.com/improving-the-performance-of-a-windows-10-guest-on-qemu-a5b3f54d9cf5
https://mathiashueber.com/performance-tweaks-gaming-on-virtual-machines/
https://github.com/avarghesein/-NIX/blob/main/Lubuntu%2020.04/Virtualization/Qemu-KVM/Performance%20Optimization%20-%20Qemu-KVM%20Guests.md


I read the qemu changelog and there are no entries about performance improvement, but there are bugfixes and new feature

**Comment by uragan1987** [comment]
thx guys, thats all i want to know, i fine with 7.0.0
@romanholidaypancakes i got this informations too, anyway, THX for your work

@zhaodice thx for the patches,  i did it 3-4 months by hand,  and later found your github page 😃

Currently i search for CPUID setup inside qemu source,  for Windows 10 guests, but this is wrong here
