### ISSUE TITLE
Detection Tool

### ISSUE THREAD

**Issue by Kwansy98** [zhaodice/qemu-anti-detection#25]
Can you provide the download link of the virtual machine detection tool used in the screenshot?

**Comment by zhaodice** [comment]
sure, but I have no sources.
[虚拟机检测工具包.zip](https://github.com/zhaodice/qemu-anti-detection/files/12226051/default.zip)
[3.4.vmp.exe.zip](https://github.com/zhaodice/qemu-anti-detection/files/12226055/3.4.vmp.exe.zip)
