### ISSUE TITLE
Gepard Block Running Windows VM

### ISSUE THREAD

**Issue by jokinvipo** [zhaodice/qemu-anti-detection#28]
Hello,

Thank you for this project.

Im trying to apply this bypass in Windows to bypass Gepard detection on VM.

Can you give me a hand with some steps ?

**Comment by zhaodice** [comment]
you NEED bypass RDTSC,see https://github.com/WCharacter/RDTSC-KVM-Handler/
(the bad side is CPU will be 0.25Ghz)
