### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Yirss** [zhaodice/qemu-anti-detection#36]
能不能给个联系方式，想交流一下，wx或者telegram

**Comment by zhaodice** [comment]
有QQ，是0x6082BD36（自己转十进制，用作反搜索引擎）。
但事实上我不专门做反检测，这只是纯粹我自己用顺带开源出来而已，你不太可能从我这里交流出这个项目里以外的反检测技术

**Comment by Yirss** [comment]
😮‍💨行吧，主要是学习目的，不打扰你了
