### ISSUE TITLE
求助 可以在已经安装好的QEMU修改配置文件来达到相同的效果吗

### ISSUE THREAD

**Issue by paradoxztj** [zhaodice/qemu-anti-detection#42]
我尝试根据补丁对qemu-kvm的包（用的是qemu7.2）进行修改，但大概有1/3的文件名有不一样 。请问有快速找到虚拟特征文件的方法吗

**Comment by zhaodice** [comment]
没什么好办法啊。。。文件名变动应该算少数情况了
