### ISSUE TITLE
Why does it not work when I follow the document

### ISSUE THREAD

**Issue by 204065248** [zhaodice/qemu-anti-detection#6]

**Comment by zhaodice** [comment]
more information required

**Comment by 204065248** [comment]
After I compiled qemu, the ASUS string was already displayed. And then set the KVM XML as the content of video at https://www.youtube.com/watch?v=Iass2FMHHng. Check tools such as SE and VMP still display the VM. Sorry, my English is not very good!

**Comment by 204065248** [comment]
And the task manager is displayed as a virtual machine

**Comment by zhaodice** [comment]
能看中文?
  <qemu:commandline>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=0,version=UX305UA.201"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=1,manufacturer=ASUS,product=UX305UA,version=2021.1"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=2,manufacturer=Intel,version=2021.5,product=Intel i9-12900K"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=3,manufacturer=XBZJ"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=000000,part=0000"/>
    <qemu:arg value="-smbios"/>
    <qemu:arg value="type=4,manufacturer=Intel,max-speed=4800,current-speed=4800"/>
    <qemu:arg value="-cpu"/>
    <qemu:arg value="host,family=6,model=158,stepping=2,model_id=Intel(R) Core(TM) i9-12900K CPU @ 2.60GHz,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,-hypervisor,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_relaxed,kvm=off,hv_vendor_id=intel"/>
    <qemu:arg value="-smp"/>
    <qemu:arg value="12,cores=12,threads=1,sockets=1"/>
    <qemu:arg value="-machine"/>
    <qemu:arg value="q35,kernel_irqchip=on"/>
    <qemu:arg value="-acpitable"/>
    <qemu:arg value="file=/passthough/ssdt1.dat"/>
    <qemu:env name="DISPLAY" value=":0.0"/>
    <qemu:env name="MESA_LOADER_DRIVER_OVERRIDE" value="i965"/>
  </qemu:commandline>
过检测除了自己编译qemu，xml主要是要加这个

**Comment by zhaodice** [comment]
然后
```
   <qemu:arg value="-acpitable"/>
    <qemu:arg value="file=/passthough/ssdt1.dat"/>
```
这个可以不写，这个主要是用来伪装充电的，让N卡驱动始终以为自己插着电源，这样可以一直满血

**Comment by 204065248** [comment]
这个我一开始就试了试。但是一保存他就自动帮我删除了 - -

**Comment by zhaodice** [comment]
按错了-。-，你这种情况需要新建虚拟机那个时候就要修改xml，建完好像有bug改不了

**Comment by 204065248** [comment]
> 按错了-。-，你这种情况需要新建虚拟机那个时候就要修改xml，建完好像有bug改不了

原来如此，不过我刚刚试了试用指令修改，修改成功了，不能用GUI修改了。就是ssdt1.dat文件不存在可以教教怎么搞吗

**Comment by zhaodice** [comment]
> > 按错了-。-，你这种情况需要新建虚拟机那个时候就要修改xml，建完好像有bug改不了
> 
> 原来如此，不过我刚刚试了试用指令修改，修改成功了，不能用GUI修改了。就是ssdt1.dat文件不存在可以教教怎么搞吗

https://lantian.pub/usr/uploads/202007/ssdt1.dat

**Comment by zhaodice** [comment]
自己下载自己放到指定路径

**Comment by 204065248** [comment]
感谢大佬，感觉都可以去掉物理机的windows系统了。哈哈哈，有啥办法自定义硬盘的序列号吗

**Comment by zhaodice** [comment]
> 感谢大佬，感觉都可以去掉物理机的windows系统了。哈哈哈，有啥办法自定义硬盘的序列号吗

硬盘序列号和虚拟机无关，它属于一段数据写在硬盘里的，操作系统都可以改，具体自己百度搜吧
https://blog.csdn.net/novanova2009/article/details/113714428

**Comment by 204065248** [comment]
好的，感谢
