### ISSUE TITLE
Not working on Anti Cheat Expert?

### ISSUE THREAD

**Issue by Weroxig** [zhaodice/qemu-anti-detection#61]
I tried to play Nikke using this project but after logging in and pressing "launch" the main game client opens up but it is stuck loading infinitely. Could you have a try on your virtual machine? the game is only a few gb.

**Comment by zhaodice** [comment]
ACE has diffent detection levels ,example , VALORANT has the higher detection level than CrossFire(CF) from ACE, and VALORANT ACE shows "cannot run under virtual machine" but CrossFire is ok...
you can enable the hyper-v and try again( but maybe enconter the blue screen)

**Comment by whyisshen** [comment]
> ACE has diffent detection levels ,example , VALORANT has the higher detection level than CrossFire(CF) from ACE, and VALORANT ACE shows "cannot run under virtual machine" but CrossFire is ok... you can enable the hyper-v and try again( but maybe enconter the blue screen)

大佬怎么才能过CF的检测,我启动的时候总是提示游戏不支持运行在虚拟机中,但是其他的虚拟机检测软件都通过了...

**Comment by zhaodice** [comment]
> > ACE has diffent detection levels ,example , VALORANT has the higher detection level than CrossFire(CF) from ACE, and VALORANT ACE shows "cannot run under virtual machine" but CrossFire is ok... you can enable the hyper-v and try again( but maybe enconter the blue screen)
> 
> 大佬怎么才能过CF的检测,我启动的时候总是提示游戏不支持运行在虚拟机中,但是其他的虚拟机检测软件都通过了...

我几个月前试了CF没问题，但是无畏契约的ACE报告虚拟机，我不知道新的更新了啥，也许CF现在也跟上了吧，我不清楚

**Comment by Weroxig** [comment]
Needed to install vcrun redists

**Comment by t106362512** [comment]
Starting from May 30, not working after updating the Nikke launcher. (Got 13-131223-22)
