### ISSUE TITLE
请求更新到9.0.0

### ISSUE THREAD

**Issue by Zhaodaidai** [zhaodice/qemu-anti-detection#62]
麻烦更新一下适合最新版的补丁可以吗，一直在用你的8.2.0版本

**Comment by zhaodice** [comment]
这个。。也不难的其实，你patch的时候看看哪里报错你就对应的去手动改对应的c源码（根据patch给的线索）。。就行了

**Comment by Zhaodaidai** [comment]
好的呢 谢谢
