### ISSUE TITLE
cannot use copy and paste features with this build

### ISSUE THREAD

**Issue by FurkanCodes** [zhaodice/qemu-anti-detection#7]
Wehn spice-guest-tools installed on a windows guest machine, it seems like copy and paste does not work, is that intended? 
I deleted and used regular version of qemu and it works there.

**Comment by zhaodice** [comment]
yes,it is intended, because qemu-agent can be detected as a VirtualMachine

I recommend you use generic File/Paste transfer, rather than virtual machine agent software.

**Comment by FurkanCodes** [comment]
Thanks again. I tried Samba Server but seems like my host windows cannot connect(it does not see the samba server in the network tab), is that intended too?

Which transfer method are  you using?

**Comment by zhaodice** [comment]
it is easy to detect if you use any software that can only be used within VirtualMachine (even remains installed clue)

**Comment by zhaodice** [comment]
> Thanks again. I tried Samba Server but seems like my host windows cannot connect(it does not see the samba server in the network tab), is that intended too?
> 
> Which transfer method are you using?

Local http server and webdav

**Comment by FurkanCodes** [comment]
So I cannot use Samba server as well? What kind of sharing are you using with this? I have been creating .isos and transferring between machines

**Comment by FurkanCodes** [comment]
Thank you. I will look into those. Do you have any idea why samba server would not work? I think the principle is the same, is not it

**Comment by zhaodice** [comment]
you can use NAT network , assume your host nat gataway is 192.168.122.1, your virtual machine can connect it if your host listened it

**Comment by zhaodice** [comment]
> Thank you. I will look into those. Do you have any idea why samba server would not work? I think the principle is the same, is not it

I think network discovering doesn't work, you can connect it with ip

**Comment by FurkanCodes** [comment]
All right, I will look into those methods as well. Thank you! 

Have you patched any CPU categorizations? Is it advised  to run games on this?

**Comment by FurkanCodes** [comment]
thank you, I should just add it as well just in case

**Comment by FurkanCodes** [comment]
I have gotten to work it after 2 days of endless struggle. I also set up Looking glass, easy anti cheat does not detect it. Amazing job, really!
