### ISSUE TITLE
ssdt

### ISSUE THREAD

**Issue by AndreyRz** [zhaodice/qemu-anti-detection#8]
<qemu:arg value="-acpitable"/>
    <qemu:arg value="file=/passthough/ssdt1.dat"/>
Can you please share this file? As I understand it has additional adjustments for acpi tables.

**Comment by zhaodice** [comment]
https://lantian.pub/usr/uploads/202007/ssdt1.dat

**Comment by AndreyRz** [comment]
Do you know how to get rid of the acpi\qemu0002 device that is hidden in the windows device manager and leaves notes about itself in the registry?

**Comment by zhaodice** [comment]
use HEX editor, example GHEX, open this ssdt file and edit all of qemu

**Comment by AndreyRz** [comment]
I am not familiar with such files, what exactly do I need to change in it?

**Comment by zhaodice** [comment]
> I am not familiar with such files, what exactly do I need to change in it?

assume you are in X11 environment:
sudo apt install ghex
ghex ssdt1.dat

will open window, edit thia file and save is ok

**Comment by AndreyRz** [comment]
https://prnt.sc/QPSP8-_wqIe7 what specific lines should be edited?

**Comment by zhaodice** [comment]
> https://prnt.sc/QPSP8-_wqIe7 what specific lines should be edited?

or you can use this file which has been edited by me: https://github.com/zhaodice/qemu-anti-detection/blob/main/ssdt1.dat?raw=true

**Comment by zhaodice** [comment]
![Screenshot_20230404_041054](https://user-images.githubusercontent.com/63996691/229616594-ee9cd859-f605-449e-ad7f-83d78640f250.png)
this is my registry, did you patch your qemu by this project?

**Comment by AndreyRz** [comment]
yes

**Comment by zhaodice** [comment]
I will go sleep, you can leave your question if you encountered again.

**Comment by AndreyRz** [comment]
https://prnt.sc/GPCFkCaEZjXm that with qemu patch without ssdt file

**Comment by zhaodice** [comment]
ok,It is a problem, I am trying to find it

**Comment by zhaodice** [comment]
NEWPATCH: https://github.com/zhaodice/qemu-anti-detection/blob/main/qemu7.0.0.patch

**Comment by zhaodice** [comment]
after your installing,you can remove this registry manually

**Comment by nhamhuynh79** [comment]
![Screenshot from 2023-10-19 06-10-24](https://github.com/zhaodice/qemu-anti-detection/assets/109447918/ee09bcf7-786a-49a7-8a41-ba5e10ba0dcd)
How to fix that?

**Comment by zhaodice** [comment]
> ![Screenshot from 2023-10-19 06-10-24](https://user-images.githubusercontent.com/109447918/276607616-ee09bcf7-786a-49a7-8a41-ba5e10ba0dcd.png) How to fix that?

cd ~/Downloads/
chmod 777 ssdt1.dat

**Comment by nhamhuynh79** [comment]
> > ![Screenshot from 2023-10-19 06-10-24](https://user-images.githubusercontent.com/109447918/276607616-ee09bcf7-786a-49a7-8a41-ba5e10ba0dcd.png) How to fix that?
> 
> cd ~/Downloads/ chmod 777 ssdt1.dat
Still permission denied

**Comment by zhaodice** [comment]
@nhamhuynh79 
```
cd ~/Downloads/work
chmod 777 ssdt1.dat
```
please show :
```
ls -l
```
