### ISSUE TITLE
Warning KVM is not availabe

### ISSUE THREAD

**Issue by SOUZEGB** [zhaodice/qemu-anti-detection#86]
Hi guys i have problem with qemu/kvm after successfully installed my qemu/kvm and patched/build anti-detection qemu i dont have kvm available:

![Screenshot from 2024-06-30 20-03-21](https://github.com/zhaodice/qemu-anti-detection/assets/138151932/9407ceef-bddd-4c8e-8e47-f9175a539578)

i was trying to reinstalling everything and see if that change something then patched again but still is same issue and i dont know how to fix that thanks for reply and help.

Linux: Ubuntu 24.04

**Comment by zhaodice** [comment]
did you try install qemu only without kvm package?( I didn't release any kvm program patch I think...)

**Comment by SOUZEGB** [comment]
> did you try install qemu only without kvm package?( I didn't release any kvm program patch I think...)

after uninstalling qemu-kvm i got this error 

Error launching details: Host does not support virtualization type 'hvm' for architecture 'x86_64'

**Comment by SOUZEGB** [comment]
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-sparc for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-sparc: Pe>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: Failed to probe capabilities for /usr/local/bin/qemu-system-sparc: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-sparc for probing: libvirt: >
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-sparc64 for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-sparc64>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: Failed to probe capabilities for /usr/local/bin/qemu-system-sparc64: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-sparc64 for probing: libvi>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-x86_64 for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-x86_64: >
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: Failed to probe capabilities for /usr/local/bin/qemu-system-x86_64: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-x86_64 for probing: libvirt>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-xtensa for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-xtensa: >
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: Failed to probe capabilities for /usr/local/bin/qemu-system-xtensa: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-xtensa for probing: libvirt>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-xtensaeb for probing: libvirt:  error : cannot execute binary /usr/local/bin/qemu-system-xtensa>
Jul 09 23:43:27 SOUZEGB-PC libvirtd[48755]: Failed to probe capabilities for /usr/local/bin/qemu-system-xtensaeb: internal error: Failed to start QEMU binary /usr/local/bin/qemu-system-xtensaeb for probing: lib>

**Comment by zhaodice** [comment]
https://discussion.fedoraproject.org/t/valueerror-host-does-not-support-virtualization-type-hvm-for-architecture-x86-64/84769

**Comment by SOUZEGB** [comment]
Distro is different than my i have ubuntu, above fix is for fedora

@edit
On manjaro is everything working well without any issue but i need ubuntu for secure boot, and dual gpu passthrough thats why I prefer using ubuntu there is no issue with that combo but building and patches on ubuntu seems doesn't work properly like on manjaro.
