### ISSUE TITLE
Error: Host does not support virtualization type ‘hvm’ for architecture ‘x86_64’

### ISSUE THREAD

**Issue by barclayiversen** [zhaodice/qemu-anti-detection#89]
I'm on a fresh install of ubuntu 24. I had qemu running a single VM configured via virt-manager before I patched. After I patched virt-manager was unable to open the VM and gave me the error in the title.

I deleted the patched binary, reinstalled via package manager and the issue went away. 

Some things to note:
- the VM was actually still able to start via "virsh start" but I couldn't use virt-manager to view the details or configure it. 
- I'm on version 8.2.2 of qemu. I used the 8.2.0 patch

**Comment by Berikai** [comment]
I have experienced exactly the same problem on QEMU 9.0.2 with [this 9.0.1 patch](https://github.com/zhaodice/qemu-anti-detection/issues/87#issuecomment-2211538092). VM is able to start but configuration tab gives mentioned error. Don't know what causes this and what is the fix but I hope it can be resolved.

**Comment by SOUZEGB** [comment]
https://github.com/Scrut1ny/Hypervisor-Phantom run script Auto-Hypervisor.sh before running this script remove qemu binary

**Comment by barclayiversen** [comment]
I found a workaround. Downgrading my linux kernel to 6.0.0 has resolved the virt-manager issue I was facing.

**Comment by coinstore** [comment]
Alternative fix here: https://github.com/zhaodice/qemu-anti-detection/issues/91#issuecomment-5752940752
